// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:cs2_rcon_front_end/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MessageAdapter());
    registerAdapter(SavedMessageAdapter());
    registerAdapter(SenderAdapter());
    registerAdapter(ServerAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MessageAdapter());
    registerAdapter(SavedMessageAdapter());
    registerAdapter(SenderAdapter());
    registerAdapter(ServerAdapter());
  }
}
