display_name: Arkie
package_name: arkie

maintainer:
  name: Elyon Labs, LLC
  email: support@elyon-labs.com

priority: optional

section: x11

installed_size: 15700

essential: false

icon: assets/rcon_icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - RCON
  - CS2

generic_name: Arkie RCON Client

categories:
  - Development
  - Utility

startup_notify: true